### ISSUE TITLE
variant calling from multiple files using snippy

### ISSUE THREAD

**Issue by sekhwal** [vappiah/variant-calling#1]
Hi,

I am following your videos and they are very helpful for me especially to understand fundamental bioinformatics. I am trying to run snippy with multiple files using "snippy-multi input.tab --ref Reference.gbk --cpus 16 > runme.sh". After running snippy it gives me VARIANTS 0 in core.txt for reference. I am not sure if it is normal or something wrong with snippy installation. I am wondering if you can help me in this issue.
--------------
head core.txt
ID	        LENGTH	             ALIGNED	UNALIGNED	 VARIANT	HET	MASKED	LOWCOV
Sm_010	        4951383	     4470711	458441	         40566	8577	0	13654
Sm_012	        4951383	     4477314	457844	         40532	6843	0	9382
Reference	4951383	     4951383	0	                 0	        0	        0	0

Thank you,

**Comment by vappiah** [comment]
Hi @sekhwal I suggest you raise an issue on the software [developer's page](https://github.com/tseemann/snippy/issues)

If they are still unable resolve, you can book a session with me and we can resolve it together.

**Comment by sekhwal** [comment]
Thank you for your suggestion.
